services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    volumes:
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf 
      - ./ports.conf:/etc/apache2/ports.conf 
    restart: always
    network_mode: "host"
  haproxy:
    image: haproxytech/haproxy-alpine:2.4
    container_name: haproxy
    volumes:
      - ./haproxy/etc:/usr/local/etc/haproxy:ro
    restart: always
    network_mode: "host"
