version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
    volumes:
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf 
      - ./ports.conf:/etc/apache2/ports.conf 
    restart: always
    network_mode: "host"
